import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const exercises = [
  // PUSH (40)
  { name: 'Barbell Bench Press', name_da: 'Bænkpres med vægtstang', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','front delts'], equipment: ['barbell','bench'], difficulty: 'intermediate', instructions: 'Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up.', form_cues: ['Retract shoulder blades','Feet flat on floor','Drive through chest'] },
  { name: 'Incline Barbell Bench Press', name_da: 'Skrå bænkpres med vægtstang', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['triceps','front delts'], equipment: ['barbell','incline bench'], difficulty: 'intermediate', instructions: 'Set bench to 30-45 degrees, press bar from upper chest.', form_cues: ['Keep elbows at 45 degrees','Control the negative'] },
  { name: 'Decline Barbell Bench Press', name_da: 'Decline bænkpres', category: 'push', muscle_groups: ['lower chest'], secondary_muscles: ['triceps','front delts'], equipment: ['barbell','decline bench'], difficulty: 'intermediate', instructions: 'Set bench to decline, press bar from lower chest.', form_cues: ['Secure legs','Control the bar path'] },
  { name: 'Dumbbell Bench Press', name_da: 'Bænkpres med håndvægte', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','front delts'], equipment: ['dumbbells','bench'], difficulty: 'beginner', instructions: 'Press dumbbells up from chest level, squeeze at top.', form_cues: ['Keep wrists neutral','Full range of motion'] },
  { name: 'Incline Dumbbell Press', name_da: 'Skrå bænkpres med håndvægte', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['triceps','front delts'], equipment: ['dumbbells','incline bench'], difficulty: 'beginner', instructions: 'Press dumbbells on incline bench, focus on upper chest squeeze.', form_cues: ['30-45 degree angle','Control the weight'] },
  { name: 'Dumbbell Flyes', name_da: 'Flyes med håndvægte', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['dumbbells','bench'], difficulty: 'beginner', instructions: 'Open arms wide with slight bend in elbows, squeeze chest to close.', form_cues: ['Slight bend in elbows','Feel the stretch'] },
  { name: 'Incline Dumbbell Flyes', name_da: 'Skrå flyes med håndvægte', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['front delts'], equipment: ['dumbbells','incline bench'], difficulty: 'beginner', instructions: 'Perform flyes on incline bench targeting upper chest.', form_cues: ['Control the arc','Squeeze at top'] },
  { name: 'Cable Flyes', name_da: 'Kabel flyes', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Set cables at chest height, bring handles together in front.', form_cues: ['Lean slightly forward','Squeeze chest'] },
  { name: 'Low Cable Flyes', name_da: 'Lave kabel flyes', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['front delts'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Set cables low, bring handles up and together.', form_cues: ['Arc motion upward','Constant tension'] },
  { name: 'High Cable Flyes', name_da: 'Høje kabel flyes', category: 'push', muscle_groups: ['lower chest'], secondary_muscles: ['front delts'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Set cables high, bring handles down and together.', form_cues: ['Control the motion','Squeeze at bottom'] },
  { name: 'Push-Ups', name_da: 'Armstrækninger', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','front delts','core'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Hands shoulder-width, lower chest to floor, push up.', form_cues: ['Keep body straight','Full range of motion'] },
  { name: 'Diamond Push-Ups', name_da: 'Diamant armstrækninger', category: 'push', muscle_groups: ['triceps'], secondary_muscles: ['chest','front delts'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Hands together forming diamond shape, push up.', form_cues: ['Elbows close to body','Control the movement'] },
  { name: 'Decline Push-Ups', name_da: 'Decline armstrækninger', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['triceps','front delts'], equipment: ['bodyweight','bench'], difficulty: 'intermediate', instructions: 'Feet elevated on bench, perform push-ups.', form_cues: ['Keep core tight','Control descent'] },
  { name: 'Military Press', name_da: 'Militærpres', category: 'push', muscle_groups: ['front delts'], secondary_muscles: ['triceps','upper chest'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Press barbell overhead from front of shoulders.', form_cues: ['Brace core','Full lockout'] },
  { name: 'Overhead Press', name_da: 'Overhead pres', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps','upper chest'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Standing barbell press overhead.', form_cues: ['Squeeze glutes','Press straight up'] },
  { name: 'Dumbbell Shoulder Press', name_da: 'Skulder pres med håndvægte', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Press dumbbells overhead from shoulder height.', form_cues: ['Neutral grip option','Full extension'] },
  { name: 'Arnold Press', name_da: 'Arnold pres', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps','front delts'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: 'Rotate palms during press from front to overhead.', form_cues: ['Smooth rotation','Control throughout'] },
  { name: 'Lateral Raises', name_da: 'Lateral raises', category: 'push', muscle_groups: ['side delts'], secondary_muscles: ['traps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Raise dumbbells to sides until parallel with floor.', form_cues: ['Slight bend in elbows','Lead with elbows'] },
  { name: 'Cable Lateral Raises', name_da: 'Kabel lateral raises', category: 'push', muscle_groups: ['side delts'], secondary_muscles: ['traps'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Single arm lateral raise using low cable.', form_cues: ['Constant tension','Control the negative'] },
  { name: 'Front Raises', name_da: 'Front raises', category: 'push', muscle_groups: ['front delts'], secondary_muscles: ['upper chest'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Raise dumbbells in front to shoulder height.', form_cues: ['Alternate arms','No swinging'] },
  { name: 'Tricep Dips', name_da: 'Tricep dips', category: 'push', muscle_groups: ['triceps'], secondary_muscles: ['chest','front delts'], equipment: ['dip station'], difficulty: 'intermediate', instructions: 'Lower body between parallel bars, press up.', form_cues: ['Elbows back not flared','Upright torso for triceps'] },
  { name: 'Chest Dips', name_da: 'Bryst dips', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','front delts'], equipment: ['dip station'], difficulty: 'intermediate', instructions: 'Lean forward during dips to target chest.', form_cues: ['Lean forward','Deep stretch at bottom'] },
  { name: 'Tricep Pushdowns', name_da: 'Tricep pushdowns', category: 'push', muscle_groups: ['triceps'], secondary_muscles: null, equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Push cable attachment down, extending elbows fully.', form_cues: ['Keep elbows pinned','Squeeze at bottom'] },
  { name: 'Overhead Tricep Extension', name_da: 'Overhead tricep extension', category: 'push', muscle_groups: ['triceps'], secondary_muscles: null, equipment: ['dumbbell'], difficulty: 'beginner', instructions: 'Hold dumbbell overhead, lower behind head, extend.', form_cues: ['Keep elbows close','Full stretch'] },
  { name: 'Skull Crushers', name_da: 'Skull crushers', category: 'push', muscle_groups: ['triceps'], secondary_muscles: null, equipment: ['ez-bar','bench'], difficulty: 'intermediate', instructions: 'Lower bar to forehead, extend arms.', form_cues: ['Keep elbows steady','Control the weight'] },
  { name: 'Close Grip Bench Press', name_da: 'Tæt greb bænkpres', category: 'push', muscle_groups: ['triceps'], secondary_muscles: ['chest','front delts'], equipment: ['barbell','bench'], difficulty: 'intermediate', instructions: 'Bench press with narrow grip targeting triceps.', form_cues: ['Hands shoulder-width','Elbows close to body'] },
  { name: 'Cable Tricep Kickbacks', name_da: 'Kabel tricep kickbacks', category: 'push', muscle_groups: ['triceps'], secondary_muscles: null, equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Extend arm back using cable, squeeze tricep.', form_cues: ['Keep upper arm still','Full extension'] },
  { name: 'Machine Chest Press', name_da: 'Maskine brystpres', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','front delts'], equipment: ['chest press machine'], difficulty: 'beginner', instructions: 'Press handles forward on chest press machine.', form_cues: ['Set seat height correctly','Full range of motion'] },
  { name: 'Machine Shoulder Press', name_da: 'Maskine skulder pres', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps'], equipment: ['shoulder press machine'], difficulty: 'beginner', instructions: 'Press handles overhead on shoulder press machine.', form_cues: ['Back against pad','Full lockout'] },
  { name: 'Pec Deck', name_da: 'Pec deck', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['pec deck machine'], difficulty: 'beginner', instructions: 'Bring arms together on pec deck machine.', form_cues: ['Squeeze at center','Control the return'] },
  { name: 'Landmine Press', name_da: 'Landmine pres', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['shoulders','triceps'], equipment: ['barbell','landmine'], difficulty: 'intermediate', instructions: 'Press barbell up using landmine attachment.', form_cues: ['Stagger stance','Press at angle'] },
  { name: 'Single Arm Dumbbell Press', name_da: 'Enkelt arm dumbbell pres', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps','core'], equipment: ['dumbbell','bench'], difficulty: 'intermediate', instructions: 'Press one dumbbell at a time on bench.', form_cues: ['Brace core','Control rotation'] },
  { name: 'Floor Press', name_da: 'Gulv pres', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['triceps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Press dumbbells lying on floor, limited ROM.', form_cues: ['Elbows touch floor','Pause at bottom'] },
  { name: 'Svend Press', name_da: 'Svend pres', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['weight plate'], difficulty: 'beginner', instructions: 'Squeeze plate between palms, press forward.', form_cues: ['Squeeze hard','Slow tempo'] },
  { name: 'Pike Push-Ups', name_da: 'Pike armstrækninger', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Push-ups with hips elevated targeting shoulders.', form_cues: ['Hips high','Head between arms'] },
  { name: 'Handstand Push-Ups', name_da: 'Håndstand armstrækninger', category: 'push', muscle_groups: ['shoulders'], secondary_muscles: ['triceps','core'], equipment: ['bodyweight','wall'], difficulty: 'advanced', instructions: 'Push-ups in handstand position against wall.', form_cues: ['Core tight','Control descent'] },
  { name: 'JM Press', name_da: 'JM pres', category: 'push', muscle_groups: ['triceps'], secondary_muscles: ['chest'], equipment: ['barbell','bench'], difficulty: 'advanced', instructions: 'Hybrid of close grip bench and skull crusher.', form_cues: ['Lower to chin level','Elbows forward'] },
  { name: 'Dumbbell Pullover', name_da: 'Dumbbell pullover', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['lats','triceps'], equipment: ['dumbbell','bench'], difficulty: 'intermediate', instructions: 'Extend dumbbell over and behind head, pull back.', form_cues: ['Keep slight bend in elbows','Feel the stretch'] },
  { name: 'Cable Crossover', name_da: 'Kabel crossover', category: 'push', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Cross cables from high position in front of body.', form_cues: ['Lean forward slightly','Cross hands over'] },
  { name: 'Reverse Grip Bench Press', name_da: 'Reverse greb bænkpres', category: 'push', muscle_groups: ['upper chest'], secondary_muscles: ['triceps'], equipment: ['barbell','bench'], difficulty: 'advanced', instructions: 'Bench press with underhand grip.', form_cues: ['Use spotter','Grip firmly'] },

  // PULL (40)
  { name: 'Barbell Bent-Over Row', name_da: 'Bøjet roning med vægtstang', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Hinge at hips, pull bar to lower chest.', form_cues: ['Keep back flat','Squeeze shoulder blades'] },
  { name: 'Dumbbell Row', name_da: 'Håndvægt roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['dumbbell','bench'], difficulty: 'beginner', instructions: 'One arm row with knee on bench.', form_cues: ['Pull to hip','Keep back flat'] },
  { name: 'Pendlay Row', name_da: 'Pendlay roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Explosive row from floor each rep.', form_cues: ['Reset each rep','Explosive pull'] },
  { name: 'T-Bar Row', name_da: 'T-bar roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['t-bar','landmine'], difficulty: 'intermediate', instructions: 'Straddle bar, row to chest.', form_cues: ['Keep chest up','Squeeze at top'] },
  { name: 'Seated Cable Row', name_da: 'Siddende kabel roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Pull cable handle to midsection while seated.', form_cues: ['Sit tall','Pull to belly button'] },
  { name: 'Lat Pulldown', name_da: 'Lat pulldown', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps','rear delts'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Pull bar down to upper chest.', form_cues: ['Lean back slightly','Pull elbows down'] },
  { name: 'Close Grip Lat Pulldown', name_da: 'Tæt greb lat pulldown', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps'], equipment: ['cable machine','v-bar'], difficulty: 'beginner', instructions: 'Lat pulldown with close neutral grip.', form_cues: ['Pull to sternum','Squeeze lats'] },
  { name: 'Wide Grip Lat Pulldown', name_da: 'Bredt greb lat pulldown', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps','rear delts'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Lat pulldown with wide overhand grip.', form_cues: ['Full stretch at top','Pull to collarbone'] },
  { name: 'Pull-Ups', name_da: 'Pull-ups', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps','rear delts','core'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: 'Hang from bar, pull chin above bar.', form_cues: ['Full dead hang','Lead with chest'] },
  { name: 'Chin-Ups', name_da: 'Chin-ups', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: 'Underhand grip pull-up.', form_cues: ['Supinated grip','Full extension at bottom'] },
  { name: 'Neutral Grip Pull-Ups', name_da: 'Neutral greb pull-ups', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['biceps','rear delts'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: 'Pull-ups with palms facing each other.', form_cues: ['Palms face each other','Full range of motion'] },
  { name: 'Face Pulls', name_da: 'Face pulls', category: 'pull', muscle_groups: ['rear delts'], secondary_muscles: ['traps','rhomboids'], equipment: ['cable machine','rope'], difficulty: 'beginner', instructions: 'Pull rope to face, externally rotate at top.', form_cues: ['High elbow position','External rotation at top'] },
  { name: 'Reverse Flyes', name_da: 'Reverse flyes', category: 'pull', muscle_groups: ['rear delts'], secondary_muscles: ['rhomboids','traps'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Bent over, raise dumbbells to sides.', form_cues: ['Slight bend in elbows','Squeeze shoulder blades'] },
  { name: 'Cable Reverse Flyes', name_da: 'Kabel reverse flyes', category: 'pull', muscle_groups: ['rear delts'], secondary_muscles: ['rhomboids'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Cross cables, pull apart at face height.', form_cues: ['Keep arms straight','Control the movement'] },
  { name: 'Barbell Curl', name_da: 'Bicep curl med vægtstang', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['forearms'], equipment: ['barbell'], difficulty: 'beginner', instructions: 'Curl barbell from thighs to shoulders.', form_cues: ['Keep elbows pinned','No swinging'] },
  { name: 'Dumbbell Curl', name_da: 'Bicep curl med håndvægte', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['forearms'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Curl dumbbells alternating or together.', form_cues: ['Supinate at top','Control negative'] },
  { name: 'Hammer Curl', name_da: 'Hammer curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['brachialis','forearms'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Curl with neutral grip.', form_cues: ['Thumbs up grip','No swinging'] },
  { name: 'Preacher Curl', name_da: 'Preacher curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['forearms'], equipment: ['ez-bar','preacher bench'], difficulty: 'beginner', instructions: 'Curl on preacher bench for isolation.', form_cues: ['Full extension','Slow negative'] },
  { name: 'Concentration Curl', name_da: 'Koncentrations curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: null, equipment: ['dumbbell'], difficulty: 'beginner', instructions: 'Curl with elbow braced against inner thigh.', form_cues: ['Squeeze at top','Slow and controlled'] },
  { name: 'Incline Dumbbell Curl', name_da: 'Skrå dumbbell curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['forearms'], equipment: ['dumbbells','incline bench'], difficulty: 'intermediate', instructions: 'Curl dumbbells while lying on incline bench.', form_cues: ['Arms hang naturally','Full stretch'] },
  { name: 'Cable Curl', name_da: 'Kabel curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: ['forearms'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Curl using low cable attachment.', form_cues: ['Constant tension','Squeeze at top'] },
  { name: 'Spider Curl', name_da: 'Spider curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: null, equipment: ['ez-bar','incline bench'], difficulty: 'intermediate', instructions: 'Curl draped over incline bench face down.', form_cues: ['No momentum','Peak contraction'] },
  { name: 'Barbell Shrug', name_da: 'Barbell shrugs', category: 'pull', muscle_groups: ['traps'], secondary_muscles: null, equipment: ['barbell'], difficulty: 'beginner', instructions: 'Shrug shoulders up with barbell.', form_cues: ['Straight up motion','Hold at top'] },
  { name: 'Dumbbell Shrug', name_da: 'Dumbbell shrugs', category: 'pull', muscle_groups: ['traps'], secondary_muscles: null, equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Shrug shoulders up with dumbbells.', form_cues: ['Ears to shoulders','Pause at top'] },
  { name: 'Straight Arm Pulldown', name_da: 'Straight arm pulldown', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['rear delts','core'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Pull bar down with straight arms.', form_cues: ['Keep arms straight','Squeeze lats at bottom'] },
  { name: 'Single Arm Cable Row', name_da: 'Enkelt arm kabel roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','core'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Row with one arm on cable machine.', form_cues: ['Rotate slightly','Full stretch'] },
  { name: 'Meadows Row', name_da: 'Meadows roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['barbell','landmine'], difficulty: 'advanced', instructions: 'Single arm landmine row in staggered stance.', form_cues: ['Stagger stance','Pull to hip'] },
  { name: 'Chest Supported Row', name_da: 'Bryst-støttet roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['dumbbells','incline bench'], difficulty: 'beginner', instructions: 'Row dumbbells while lying face down on incline bench.', form_cues: ['No momentum possible','Squeeze shoulder blades'] },
  { name: 'Inverted Row', name_da: 'Inverteret roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','core'], equipment: ['barbell','rack'], difficulty: 'beginner', instructions: 'Row body up to bar from underneath.', form_cues: ['Keep body straight','Pull chest to bar'] },
  { name: 'Seal Row', name_da: 'Seal roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['dumbbells','bench'], difficulty: 'intermediate', instructions: 'Row lying face down on elevated bench.', form_cues: ['No cheating','Full range of motion'] },
  { name: 'Bayesian Curl', name_da: 'Bayesian curl', category: 'pull', muscle_groups: ['biceps'], secondary_muscles: null, equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Cable curl with arm behind body for stretch.', form_cues: ['Step forward from cable','Full stretch at bottom'] },
  { name: 'Reverse Curl', name_da: 'Reverse curl', category: 'pull', muscle_groups: ['forearms'], secondary_muscles: ['biceps'], equipment: ['barbell'], difficulty: 'beginner', instructions: 'Curl with overhand grip.', form_cues: ['Overhand grip','Control the weight'] },
  { name: 'Wrist Curl', name_da: 'Håndled curl', category: 'pull', muscle_groups: ['forearms'], secondary_muscles: null, equipment: ['barbell'], difficulty: 'beginner', instructions: 'Curl wrists with forearms on bench.', form_cues: ['Forearms on bench','Small range of motion'] },
  { name: 'Machine Row', name_da: 'Maskine roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps'], equipment: ['row machine'], difficulty: 'beginner', instructions: 'Row using seated machine.', form_cues: ['Chest against pad','Full squeeze'] },
  { name: 'Rack Pull', name_da: 'Rack pull', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['traps','glutes','hamstrings'], equipment: ['barbell','rack'], difficulty: 'intermediate', instructions: 'Deadlift from elevated pins.', form_cues: ['Set pins at knee height','Drive hips through'] },
  { name: 'Band Pull-Apart', name_da: 'Band pull-apart', category: 'pull', muscle_groups: ['rear delts'], secondary_muscles: ['rhomboids','traps'], equipment: ['resistance band'], difficulty: 'beginner', instructions: 'Pull band apart at chest height.', form_cues: ['Squeeze shoulder blades','Keep arms straight'] },
  { name: 'Kroc Row', name_da: 'Kroc roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','grip'], equipment: ['dumbbell'], difficulty: 'advanced', instructions: 'Heavy single arm row with body english allowed.', form_cues: ['Heavy weight','Controlled cheating'] },
  { name: 'Cable Pullover', name_da: 'Kabel pullover', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['chest','triceps'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Pull cable from overhead to hips with straight arms.', form_cues: ['Slight bend in elbows','Squeeze lats'] },
  { name: 'Helms Row', name_da: 'Helms roning', category: 'pull', muscle_groups: ['back'], secondary_muscles: ['biceps','rear delts'], equipment: ['dumbbells','incline bench'], difficulty: 'intermediate', instructions: 'Chest supported row on 30-degree bench.', form_cues: ['Chest on bench','Pull to waist'] },
  { name: 'Behind the Neck Lat Pulldown', name_da: 'Bag nakke lat pulldown', category: 'pull', muscle_groups: ['lats'], secondary_muscles: ['rear delts'], equipment: ['cable machine'], difficulty: 'advanced', instructions: 'Pull bar behind neck carefully.', form_cues: ['Requires good mobility','Light weight'] },

  // LEGS (45)
  { name: 'Barbell Back Squat', name_da: 'Back squat med vægtstang', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings','core'], equipment: ['barbell','squat rack'], difficulty: 'intermediate', instructions: 'Bar on upper back, squat to parallel or below.', form_cues: ['Chest up','Knees track over toes','Drive through heels'] },
  { name: 'Front Squat', name_da: 'Front squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','core'], equipment: ['barbell','squat rack'], difficulty: 'advanced', instructions: 'Bar on front of shoulders, squat upright.', form_cues: ['Elbows high','Stay upright','Deep squat'] },
  { name: 'Goblet Squat', name_da: 'Goblet squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','core'], equipment: ['dumbbell'], difficulty: 'beginner', instructions: 'Hold dumbbell at chest, squat deep.', form_cues: ['Elbows inside knees','Stay upright'] },
  { name: 'Bulgarian Split Squat', name_da: 'Bulgarske split squats', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['dumbbells','bench'], difficulty: 'intermediate', instructions: 'Rear foot elevated, lunge down.', form_cues: ['Torso upright','Front knee over ankle'] },
  { name: 'Walking Lunges', name_da: 'Walking lunges', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Step forward into lunge, alternate legs.', form_cues: ['Long stride','Knee doesnt pass toe'] },
  { name: 'Reverse Lunges', name_da: 'Reverse lunges', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Step backward into lunge position.', form_cues: ['Control the step back','Upright torso'] },
  { name: 'Leg Press', name_da: 'Ben pres', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['leg press machine'], difficulty: 'beginner', instructions: 'Push platform away with feet.', form_cues: ['Dont lock knees','Full range of motion'] },
  { name: 'Hack Squat', name_da: 'Hack squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['hack squat machine'], difficulty: 'intermediate', instructions: 'Squat on hack squat machine.', form_cues: ['Back flat against pad','Deep range'] },
  { name: 'Leg Extension', name_da: 'Benstræk', category: 'legs', muscle_groups: ['quads'], secondary_muscles: null, equipment: ['leg extension machine'], difficulty: 'beginner', instructions: 'Extend legs against pad.', form_cues: ['Control the negative','Squeeze at top'] },
  { name: 'Romanian Deadlift', name_da: 'Rumænsk dødløft', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes','lower back'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Hinge at hips, lower bar along legs.', form_cues: ['Slight knee bend','Feel hamstring stretch'] },
  { name: 'Stiff Leg Deadlift', name_da: 'Stivbenet dødløft', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes','lower back'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Deadlift with minimal knee bend.', form_cues: ['Legs nearly straight','Hinge at hips'] },
  { name: 'Dumbbell Romanian Deadlift', name_da: 'Rumænsk dødløft med håndvægte', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes','lower back'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Hip hinge with dumbbells along legs.', form_cues: ['Push hips back','Keep dumbbells close'] },
  { name: 'Single Leg Romanian Deadlift', name_da: 'Etbens rumænsk dødløft', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes','core'], equipment: ['dumbbell'], difficulty: 'intermediate', instructions: 'Balance on one leg, hinge forward.', form_cues: ['Keep hips square','Slow and controlled'] },
  { name: 'Lying Leg Curl', name_da: 'Liggende bencurl', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: null, equipment: ['leg curl machine'], difficulty: 'beginner', instructions: 'Curl legs toward glutes on machine.', form_cues: ['Dont lift hips','Squeeze at top'] },
  { name: 'Seated Leg Curl', name_da: 'Siddende bencurl', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: null, equipment: ['seated leg curl machine'], difficulty: 'beginner', instructions: 'Curl legs under pad while seated.', form_cues: ['Control the negative','Full contraction'] },
  { name: 'Nordic Hamstring Curl', name_da: 'Nordisk hamstring curl', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'advanced', instructions: 'Kneel, lower body forward under control.', form_cues: ['Slow eccentric','Catch yourself at bottom'] },
  { name: 'Barbell Hip Thrust', name_da: 'Barbell hip thrust', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['barbell','bench'], difficulty: 'intermediate', instructions: 'Back on bench, thrust hips up with bar.', form_cues: ['Full hip extension','Squeeze glutes at top'] },
  { name: 'Glute Bridge', name_da: 'Glute bridge', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Lie on back, push hips up.', form_cues: ['Squeeze glutes','Hold at top'] },
  { name: 'Single Leg Glute Bridge', name_da: 'Etbens glute bridge', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings','core'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Glute bridge on one leg.', form_cues: ['Keep hips level','Full extension'] },
  { name: 'Cable Pull Through', name_da: 'Kabel pull through', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['cable machine'], difficulty: 'beginner', instructions: 'Pull cable between legs with hip hinge.', form_cues: ['Hinge at hips','Squeeze glutes'] },
  { name: 'Sumo Deadlift', name_da: 'Sumo dødløft', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['quads','hamstrings','adductors'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Wide stance deadlift.', form_cues: ['Wide stance','Push knees out'] },
  { name: 'Standing Calf Raise', name_da: 'Stående calf raise', category: 'legs', muscle_groups: ['calves'], secondary_muscles: null, equipment: ['calf raise machine'], difficulty: 'beginner', instructions: 'Rise up on toes against resistance.', form_cues: ['Full range of motion','Pause at top'] },
  { name: 'Seated Calf Raise', name_da: 'Siddende calf raise', category: 'legs', muscle_groups: ['calves'], secondary_muscles: null, equipment: ['seated calf raise machine'], difficulty: 'beginner', instructions: 'Raise heels while seated with weight on knees.', form_cues: ['Slow and controlled','Full stretch at bottom'] },
  { name: 'Donkey Calf Raise', name_da: 'Donkey calf raise', category: 'legs', muscle_groups: ['calves'], secondary_muscles: null, equipment: ['calf raise machine'], difficulty: 'intermediate', instructions: 'Calf raise in bent over position.', form_cues: ['Full range of motion','Control tempo'] },
  { name: 'Step Ups', name_da: 'Step ups', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['bench','dumbbells'], difficulty: 'beginner', instructions: 'Step up onto bench one leg at a time.', form_cues: ['Drive through front foot','Dont push off back foot'] },
  { name: 'Box Squat', name_da: 'Box squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['barbell','box'], difficulty: 'intermediate', instructions: 'Squat to box, pause, stand up.', form_cues: ['Sit back to box','Pause on box'] },
  { name: 'Sissy Squat', name_da: 'Sissy squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'advanced', instructions: 'Lean back while squatting, knees forward.', form_cues: ['Hold onto support','Lean back'] },
  { name: 'Pistol Squat', name_da: 'Pistol squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','core'], equipment: ['bodyweight'], difficulty: 'advanced', instructions: 'Single leg squat with other leg extended.', form_cues: ['Arms forward for balance','Full depth'] },
  { name: 'Leg Press Calf Raise', name_da: 'Ben pres calf raise', category: 'legs', muscle_groups: ['calves'], secondary_muscles: null, equipment: ['leg press machine'], difficulty: 'beginner', instructions: 'Calf raises on leg press machine.', form_cues: ['Toes on edge of platform','Full range of motion'] },
  { name: 'Smith Machine Squat', name_da: 'Smith maskine squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['smith machine'], difficulty: 'beginner', instructions: 'Squat using smith machine for stability.', form_cues: ['Feet slightly forward','Control the path'] },
  { name: 'Barbell Lunge', name_da: 'Barbell lunges', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','hamstrings'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Lunge with barbell on back.', form_cues: ['Upright torso','Controlled steps'] },
  { name: 'Curtsy Lunge', name_da: 'Curtsy lunge', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['quads','adductors'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: 'Lunge diagonally behind opposite leg.', form_cues: ['Cross behind','Keep torso upright'] },
  { name: 'Good Mornings', name_da: 'Good mornings', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes','lower back'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Bar on back, hinge forward at hips.', form_cues: ['Slight knee bend','Feel the stretch'] },
  { name: 'Glute Kickback Machine', name_da: 'Glute kickback maskine', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['kickback machine'], difficulty: 'beginner', instructions: 'Kick leg back against resistance.', form_cues: ['Squeeze at top','Dont arch back'] },
  { name: 'Hip Abduction Machine', name_da: 'Hofte abduktion maskine', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['abductors'], equipment: ['hip abduction machine'], difficulty: 'beginner', instructions: 'Push legs apart against resistance.', form_cues: ['Control the return','Squeeze at widest point'] },
  { name: 'Hip Adduction Machine', name_da: 'Hofte adduktion maskine', category: 'legs', muscle_groups: ['adductors'], secondary_muscles: null, equipment: ['hip adduction machine'], difficulty: 'beginner', instructions: 'Bring legs together against resistance.', form_cues: ['Control the movement','Squeeze at center'] },
  { name: 'Belt Squat', name_da: 'Belt squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['belt squat machine'], difficulty: 'intermediate', instructions: 'Squat with weight hanging from belt.', form_cues: ['No spinal load','Full depth'] },
  { name: 'Zercher Squat', name_da: 'Zercher squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','core','biceps'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Hold bar in crook of elbows, squat.', form_cues: ['Bar in elbow crease','Stay upright'] },
  { name: 'Pause Squat', name_da: 'Pause squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','core'], equipment: ['barbell','squat rack'], difficulty: 'advanced', instructions: 'Squat with 2-3 second pause at bottom.', form_cues: ['Hold position at bottom','Stay tight'] },
  { name: 'Lateral Lunge', name_da: 'Lateral lunge', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','adductors'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: 'Step to the side into lunge position.', form_cues: ['Push hips back','Keep trailing leg straight'] },
  { name: 'Wall Sit', name_da: 'Vægside', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['bodyweight','wall'], difficulty: 'beginner', instructions: 'Hold seated position against wall.', form_cues: ['90 degree angle','Back flat on wall'] },
  { name: 'Dumbbell Sumo Squat', name_da: 'Dumbbell sumo squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes','adductors'], equipment: ['dumbbell'], difficulty: 'beginner', instructions: 'Wide stance squat holding dumbbell between legs.', form_cues: ['Toes pointed out','Deep squat'] },
  { name: 'Pendulum Squat', name_da: 'Pendulum squat', category: 'legs', muscle_groups: ['quads'], secondary_muscles: ['glutes'], equipment: ['pendulum squat machine'], difficulty: 'intermediate', instructions: 'Squat on pendulum machine.', form_cues: ['Stay upright','Full depth'] },
  { name: 'Glute Ham Raise', name_da: 'Glute ham raise', category: 'legs', muscle_groups: ['hamstrings'], secondary_muscles: ['glutes'], equipment: ['GHD'], difficulty: 'advanced', instructions: 'Lower and raise body on GHD.', form_cues: ['Control eccentric','Full hip extension at top'] },
  { name: 'Cable Kickback', name_da: 'Kabel kickback', category: 'legs', muscle_groups: ['glutes'], secondary_muscles: ['hamstrings'], equipment: ['cable machine','ankle strap'], difficulty: 'beginner', instructions: 'Kick leg back using low cable.', form_cues: ['Squeeze glute','Dont arch back'] },

  // CORE (28)
  { name: 'Plank', name_da: 'Planke', category: 'core', muscle_groups: ['core'], secondary_muscles: ['shoulders'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Hold push-up position on forearms.', form_cues: ['Straight line from head to heels','Dont sag hips'] },
  { name: 'Side Plank', name_da: 'Side planke', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['core'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Hold sideways on one forearm.', form_cues: ['Hips stacked','Keep body straight'] },
  { name: 'Dead Bug', name_da: 'Dead bug', category: 'core', muscle_groups: ['core'], secondary_muscles: ['hip flexors'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Lie on back, extend opposite arm and leg.', form_cues: ['Lower back pressed to floor','Slow movement'] },
  { name: 'Bird Dog', name_da: 'Bird dog', category: 'core', muscle_groups: ['core'], secondary_muscles: ['lower back','glutes'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'On all fours, extend opposite arm and leg.', form_cues: ['Keep hips level','Slow and controlled'] },
  { name: 'Ab Wheel Rollout', name_da: 'Ab wheel rollout', category: 'core', muscle_groups: ['core'], secondary_muscles: ['lats','shoulders'], equipment: ['ab wheel'], difficulty: 'intermediate', instructions: 'Roll wheel forward, extend body, roll back.', form_cues: ['Brace core','Dont arch back'] },
  { name: 'Hanging Leg Raise', name_da: 'Hængende benløft', category: 'core', muscle_groups: ['lower abs'], secondary_muscles: ['hip flexors'], equipment: ['pull-up bar'], difficulty: 'intermediate', instructions: 'Hang from bar, raise legs to parallel.', form_cues: ['No swinging','Control the movement'] },
  { name: 'Hanging Knee Raise', name_da: 'Hængende knæløft', category: 'core', muscle_groups: ['lower abs'], secondary_muscles: ['hip flexors'], equipment: ['pull-up bar'], difficulty: 'beginner', instructions: 'Hang from bar, bring knees to chest.', form_cues: ['Curl pelvis up','No swinging'] },
  { name: 'Cable Crunch', name_da: 'Kabel crunch', category: 'core', muscle_groups: ['abs'], secondary_muscles: null, equipment: ['cable machine','rope'], difficulty: 'beginner', instructions: 'Kneel at cable, crunch down against resistance.', form_cues: ['Curl spine','Squeeze abs'] },
  { name: 'Russian Twist', name_da: 'Russisk twist', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['abs'], equipment: ['weight plate'], difficulty: 'beginner', instructions: 'Seated, rotate torso side to side with weight.', form_cues: ['Lean back slightly','Rotate fully'] },
  { name: 'Pallof Press', name_da: 'Pallof pres', category: 'core', muscle_groups: ['core'], secondary_muscles: ['obliques'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Press cable away from chest, resist rotation.', form_cues: ['Resist rotation','Brace core'] },
  { name: 'Bicycle Crunch', name_da: 'Cykel crunch', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['abs'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Alternate elbow to opposite knee.', form_cues: ['Touch elbow to knee','Slow and controlled'] },
  { name: 'Mountain Climbers', name_da: 'Mountain climbers', category: 'core', muscle_groups: ['core'], secondary_muscles: ['hip flexors','shoulders'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Run in place in push-up position.', form_cues: ['Keep hips down','Drive knees forward'] },
  { name: 'V-Ups', name_da: 'V-ups', category: 'core', muscle_groups: ['abs'], secondary_muscles: ['hip flexors'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Simultaneously raise arms and legs to form V.', form_cues: ['Touch toes','Control descent'] },
  { name: 'Toe Touches', name_da: 'Toe touches', category: 'core', muscle_groups: ['abs'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Lie on back, legs up, reach for toes.', form_cues: ['Lift shoulders off floor','Reach high'] },
  { name: 'Dragon Flag', name_da: 'Dragon flag', category: 'core', muscle_groups: ['core'], secondary_muscles: ['lower back'], equipment: ['bench'], difficulty: 'advanced', instructions: 'Lower straight body from shoulders on bench.', form_cues: ['Keep body rigid','Very slow negative'] },
  { name: 'L-Sit', name_da: 'L-sit', category: 'core', muscle_groups: ['core'], secondary_muscles: ['hip flexors','triceps'], equipment: ['dip station'], difficulty: 'advanced', instructions: 'Hold body with legs extended horizontally.', form_cues: ['Lock arms','Legs parallel to floor'] },
  { name: 'Reverse Crunch', name_da: 'Reverse crunch', category: 'core', muscle_groups: ['lower abs'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Curl hips off floor, knees toward chest.', form_cues: ['Lift hips','Control the movement'] },
  { name: 'Woodchop', name_da: 'Woodchop', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['core','shoulders'], equipment: ['cable machine'], difficulty: 'intermediate', instructions: 'Rotate and pull cable diagonally across body.', form_cues: ['Rotate through hips','Arms stay straight'] },
  { name: 'Farmers Walk', name_da: 'Farmers walk', category: 'core', muscle_groups: ['core'], secondary_muscles: ['grip','traps','legs'], equipment: ['dumbbells'], difficulty: 'beginner', instructions: 'Walk with heavy weights at sides.', form_cues: ['Stand tall','Brace core'] },
  { name: 'Suitcase Carry', name_da: 'Suitcase carry', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['core','grip'], equipment: ['dumbbell'], difficulty: 'intermediate', instructions: 'Walk with weight in one hand.', form_cues: ['Dont lean','Stay upright'] },
  { name: 'Turkish Get Up', name_da: 'Tyrkisk get up', category: 'core', muscle_groups: ['core'], secondary_muscles: ['shoulders','glutes','legs'], equipment: ['kettlebell'], difficulty: 'advanced', instructions: 'Rise from lying to standing holding weight overhead.', form_cues: ['Eyes on weight','Each step deliberate'] },
  { name: 'Decline Sit-Ups', name_da: 'Decline sit-ups', category: 'core', muscle_groups: ['abs'], secondary_muscles: ['hip flexors'], equipment: ['decline bench'], difficulty: 'intermediate', instructions: 'Sit-ups on decline bench.', form_cues: ['Cross arms on chest','Controlled movement'] },
  { name: 'Flutter Kicks', name_da: 'Flutter kicks', category: 'core', muscle_groups: ['lower abs'], secondary_muscles: ['hip flexors'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Lie on back, alternate kicking legs up and down.', form_cues: ['Lower back pressed down','Small kicks'] },
  { name: 'Hollow Body Hold', name_da: 'Hollow body hold', category: 'core', muscle_groups: ['core'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Lie on back, arms and legs extended off ground.', form_cues: ['Lower back on floor','Arms by ears'] },
  { name: 'Copenhagen Plank', name_da: 'København planke', category: 'core', muscle_groups: ['adductors'], secondary_muscles: ['obliques','core'], equipment: ['bench'], difficulty: 'advanced', instructions: 'Side plank with top leg on bench.', form_cues: ['Top leg on bench','Keep hips up'] },
  { name: 'Stir the Pot', name_da: 'Stir the pot', category: 'core', muscle_groups: ['core'], secondary_muscles: ['shoulders'], equipment: ['stability ball'], difficulty: 'intermediate', instructions: 'Plank on stability ball, make circles with arms.', form_cues: ['Small circles','Brace core'] },
  { name: 'Bear Crawl', name_da: 'Bear crawl', category: 'core', muscle_groups: ['core'], secondary_muscles: ['shoulders','quads'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Crawl forward on hands and feet, knees low.', form_cues: ['Knees off floor','Opposite hand and foot'] },
  { name: 'Windshield Wipers', name_da: 'Vinduesviskere', category: 'core', muscle_groups: ['obliques'], secondary_muscles: ['abs'], equipment: ['bodyweight'], difficulty: 'advanced', instructions: 'Lie on back, rotate legs side to side.', form_cues: ['Arms out for support','Control the rotation'] },

  // COMPOUND (18)
  { name: 'Conventional Deadlift', name_da: 'Konventionel dødløft', category: 'compound', muscle_groups: ['back','hamstrings'], secondary_muscles: ['glutes','quads','core','traps'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Lift bar from floor with flat back.', form_cues: ['Back flat','Drive through floor','Lock hips at top'] },
  { name: 'Trap Bar Deadlift', name_da: 'Trap bar dødløft', category: 'compound', muscle_groups: ['quads','back'], secondary_muscles: ['glutes','hamstrings','traps'], equipment: ['trap bar'], difficulty: 'beginner', instructions: 'Stand inside trap bar, lift.', form_cues: ['Neutral grip','Push floor away'] },
  { name: 'Power Clean', name_da: 'Power clean', category: 'compound', muscle_groups: ['back','shoulders'], secondary_muscles: ['quads','glutes','traps'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Explosive pull from floor to front rack.', form_cues: ['Triple extension','Fast elbows'] },
  { name: 'Hang Clean', name_da: 'Hang clean', category: 'compound', muscle_groups: ['back','shoulders'], secondary_muscles: ['quads','glutes','traps'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Clean from hang position.', form_cues: ['Start at knee','Explosive hip drive'] },
  { name: 'Clean and Press', name_da: 'Clean and press', category: 'compound', muscle_groups: ['full body'], secondary_muscles: ['shoulders','legs','back'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Clean bar to shoulders, then press overhead.', form_cues: ['Two distinct movements','Stable base'] },
  { name: 'Snatch', name_da: 'Snatch', category: 'compound', muscle_groups: ['full body'], secondary_muscles: ['shoulders','back','legs'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Lift bar from floor to overhead in one motion.', form_cues: ['Wide grip','Full extension','Fast turnover'] },
  { name: 'Hang Snatch', name_da: 'Hang snatch', category: 'compound', muscle_groups: ['full body'], secondary_muscles: ['shoulders','back'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Snatch from hang position.', form_cues: ['Start at hip','Explosive pull'] },
  { name: 'Thruster', name_da: 'Thruster', category: 'compound', muscle_groups: ['quads','shoulders'], secondary_muscles: ['glutes','triceps','core'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Front squat into overhead press in one motion.', form_cues: ['Deep squat','Use momentum to press'] },
  { name: 'Dumbbell Thruster', name_da: 'Dumbbell thruster', category: 'compound', muscle_groups: ['quads','shoulders'], secondary_muscles: ['glutes','triceps'], equipment: ['dumbbells'], difficulty: 'intermediate', instructions: 'Squat with dumbbells, press overhead.', form_cues: ['Smooth transition','Full lockout'] },
  { name: 'Kettlebell Swing', name_da: 'Kettlebell swing', category: 'compound', muscle_groups: ['glutes','hamstrings'], secondary_muscles: ['core','shoulders'], equipment: ['kettlebell'], difficulty: 'beginner', instructions: 'Swing kettlebell using hip hinge.', form_cues: ['Hip hinge not squat','Snap hips forward'] },
  { name: 'Man Maker', name_da: 'Man maker', category: 'compound', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['dumbbells'], difficulty: 'advanced', instructions: 'Push-up, row each side, squat clean, press.', form_cues: ['Controlled push-up','Explosive stand'] },
  { name: 'Barbell Complex', name_da: 'Barbell complex', category: 'compound', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['barbell'], difficulty: 'advanced', instructions: 'Multiple barbell movements without rest.', form_cues: ['Light weight','Focus on form'] },
  { name: 'Devils Press', name_da: 'Devils press', category: 'compound', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['dumbbells'], difficulty: 'advanced', instructions: 'Burpee with dumbbell snatch.', form_cues: ['Smooth transition','Explosive hip extension'] },
  { name: 'Push Press', name_da: 'Push pres', category: 'compound', muscle_groups: ['shoulders'], secondary_muscles: ['triceps','legs','core'], equipment: ['barbell'], difficulty: 'intermediate', instructions: 'Use leg drive to press bar overhead.', form_cues: ['Dip and drive','Full lockout'] },
  { name: 'Split Jerk', name_da: 'Split jerk', category: 'compound', muscle_groups: ['shoulders'], secondary_muscles: ['legs','core','triceps'], equipment: ['barbell'], difficulty: 'advanced', instructions: 'Drive bar overhead, split legs.', form_cues: ['Fast feet','Lock arms'] },
  { name: 'Muscle Up', name_da: 'Muscle up', category: 'compound', muscle_groups: ['lats','chest'], secondary_muscles: ['triceps','biceps','core'], equipment: ['pull-up bar'], difficulty: 'advanced', instructions: 'Pull-up transitioning above bar into dip.', form_cues: ['Kip or strict','Fast transition'] },
  { name: 'Sandbag Clean', name_da: 'Sandbag clean', category: 'compound', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['sandbag'], difficulty: 'intermediate', instructions: 'Clean sandbag to shoulders.', form_cues: ['Bear hug grip','Explosive hip drive'] },
  { name: 'Atlas Stone Lift', name_da: 'Atlas stone lift', category: 'compound', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['atlas stone'], difficulty: 'advanced', instructions: 'Lift round stone to platform or shoulders.', form_cues: ['Wrap around stone','Extend hips'] },

  // CARDIO (18)
  { name: 'Rowing Machine', name_da: 'Romaskine', category: 'cardio', muscle_groups: ['full body'], secondary_muscles: ['back','legs','core'], equipment: ['rowing machine'], difficulty: 'beginner', instructions: 'Row on ergometer with proper form.', form_cues: ['Legs-back-arms sequence','Smooth stroke'] },
  { name: 'Assault Bike', name_da: 'Assault bike', category: 'cardio', muscle_groups: ['full body'], secondary_muscles: ['legs','arms','core'], equipment: ['assault bike'], difficulty: 'beginner', instructions: 'Pedal and push/pull handles.', form_cues: ['Steady pace','Breathe rhythmically'] },
  { name: 'Battle Ropes', name_da: 'Battle ropes', category: 'cardio', muscle_groups: ['shoulders'], secondary_muscles: ['core','arms'], equipment: ['battle ropes'], difficulty: 'intermediate', instructions: 'Create waves with heavy ropes.', form_cues: ['Use whole body','Maintain rhythm'] },
  { name: 'Box Jumps', name_da: 'Box jumps', category: 'cardio', muscle_groups: ['quads'], secondary_muscles: ['glutes','calves'], equipment: ['plyo box'], difficulty: 'intermediate', instructions: 'Jump onto box, stand fully, step down.', form_cues: ['Land softly','Full hip extension on top'] },
  { name: 'Burpees', name_da: 'Burpees', category: 'cardio', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Drop to floor, push up, jump up.', form_cues: ['Chest to floor','Explosive jump'] },
  { name: 'Jump Rope', name_da: 'Sjipning', category: 'cardio', muscle_groups: ['calves'], secondary_muscles: ['shoulders','core'], equipment: ['jump rope'], difficulty: 'beginner', instructions: 'Skip rope at steady or varied pace.', form_cues: ['Wrists turn the rope','Light on feet'] },
  { name: 'Double Unders', name_da: 'Double unders', category: 'cardio', muscle_groups: ['calves'], secondary_muscles: ['shoulders','core'], equipment: ['jump rope'], difficulty: 'advanced', instructions: 'Rope passes twice per jump.', form_cues: ['Higher jump','Faster wrists'] },
  { name: 'Sled Push', name_da: 'Slæde push', category: 'cardio', muscle_groups: ['quads'], secondary_muscles: ['glutes','calves','core'], equipment: ['sled'], difficulty: 'intermediate', instructions: 'Push weighted sled across floor.', form_cues: ['Low body angle','Drive through legs'] },
  { name: 'Sled Pull', name_da: 'Slæde pull', category: 'cardio', muscle_groups: ['back'], secondary_muscles: ['biceps','legs'], equipment: ['sled','rope'], difficulty: 'intermediate', instructions: 'Pull sled toward you hand over hand.', form_cues: ['Sit back','Alternate hands'] },
  { name: 'Sprints', name_da: 'Sprints', category: 'cardio', muscle_groups: ['quads','hamstrings'], secondary_muscles: ['calves','glutes'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Run at maximum effort for short distances.', form_cues: ['Drive arms','High knees'] },
  { name: 'Hill Sprints', name_da: 'Bakke sprints', category: 'cardio', muscle_groups: ['quads','glutes'], secondary_muscles: ['calves','hamstrings'], equipment: ['bodyweight'], difficulty: 'advanced', instructions: 'Sprint up a hill, walk down to recover.', form_cues: ['Lean forward','Short powerful steps'] },
  { name: 'Stair Climber', name_da: 'Trappe maskine', category: 'cardio', muscle_groups: ['quads','glutes'], secondary_muscles: ['calves'], equipment: ['stair climber'], difficulty: 'beginner', instructions: 'Climb stairs on machine.', form_cues: ['Dont lean on handles','Steady pace'] },
  { name: 'Kettlebell Snatch', name_da: 'Kettlebell snatch', category: 'cardio', muscle_groups: ['shoulders'], secondary_muscles: ['glutes','hamstrings','core'], equipment: ['kettlebell'], difficulty: 'advanced', instructions: 'Swing kettlebell overhead in one motion.', form_cues: ['Hip drive','Punch through at top'] },
  { name: 'Treadmill Intervals', name_da: 'Løbebånd intervaller', category: 'cardio', muscle_groups: ['quads','hamstrings'], secondary_muscles: ['calves','glutes'], equipment: ['treadmill'], difficulty: 'beginner', instructions: 'Alternate fast and slow periods on treadmill.', form_cues: ['Proper footwear','Dont hold handles'] },
  { name: 'Cycling Intervals', name_da: 'Cykel intervaller', category: 'cardio', muscle_groups: ['quads'], secondary_muscles: ['hamstrings','calves'], equipment: ['stationary bike'], difficulty: 'beginner', instructions: 'Alternate high and low intensity on bike.', form_cues: ['Adjust seat height','Stay seated for power'] },
  { name: 'Jumping Jacks', name_da: 'Jumping jacks', category: 'cardio', muscle_groups: ['full body'], secondary_muscles: null, equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Jump feet apart while raising arms overhead.', form_cues: ['Land softly','Full arm extension'] },
  { name: 'High Knees', name_da: 'Høje knæ', category: 'cardio', muscle_groups: ['hip flexors'], secondary_muscles: ['core','calves'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Run in place bringing knees high.', form_cues: ['Knees to waist height','Quick tempo'] },
  { name: 'Skater Jumps', name_da: 'Skater jumps', category: 'cardio', muscle_groups: ['glutes'], secondary_muscles: ['quads','calves'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Jump laterally from foot to foot.', form_cues: ['Soft landing','Reach across body'] },

  // MOBILITY (18)
  { name: 'Foam Rolling - Quads', name_da: 'Foam rolling - quadriceps', category: 'mobility', muscle_groups: ['quads'], secondary_muscles: null, equipment: ['foam roller'], difficulty: 'beginner', instructions: 'Roll front of thighs on foam roller.', form_cues: ['Slow passes','Pause on tight spots'] },
  { name: 'Foam Rolling - IT Band', name_da: 'Foam rolling - IT band', category: 'mobility', muscle_groups: ['it band'], secondary_muscles: null, equipment: ['foam roller'], difficulty: 'beginner', instructions: 'Roll outer thigh on foam roller.', form_cues: ['Roll from hip to knee','Control pressure'] },
  { name: 'Foam Rolling - Upper Back', name_da: 'Foam rolling - øvre ryg', category: 'mobility', muscle_groups: ['upper back'], secondary_muscles: null, equipment: ['foam roller'], difficulty: 'beginner', instructions: 'Roll upper back on foam roller.', form_cues: ['Arms crossed','Extend over roller'] },
  { name: 'Hip Flexor Stretch', name_da: 'Hoftefleksor stræk', category: 'mobility', muscle_groups: ['hip flexors'], secondary_muscles: ['quads'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Kneel and push hips forward.', form_cues: ['Squeeze glute','Tall posture'] },
  { name: 'Pigeon Stretch', name_da: 'Due stræk', category: 'mobility', muscle_groups: ['glutes'], secondary_muscles: ['hip rotators'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Front leg bent, back leg extended, lean forward.', form_cues: ['Square hips','Lean forward gradually'] },
  { name: '90/90 Hip Stretch', name_da: '90/90 hofte stræk', category: 'mobility', muscle_groups: ['hips'], secondary_muscles: ['glutes'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Sit with both legs at 90 degrees, rotate.', form_cues: ['Both legs at 90 degrees','Sit tall'] },
  { name: 'World Greatest Stretch', name_da: 'Verdens bedste stræk', category: 'mobility', muscle_groups: ['hip flexors'], secondary_muscles: ['hamstrings','thoracic spine','glutes'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Lunge with rotation and hamstring stretch.', form_cues: ['Deep lunge','Rotate and reach'] },
  { name: 'Cat-Cow Stretch', name_da: 'Kat-ko stræk', category: 'mobility', muscle_groups: ['spine'], secondary_muscles: ['core'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Alternate arching and rounding spine on all fours.', form_cues: ['Breathe with movement','Flow smoothly'] },
  { name: 'Thoracic Spine Rotation', name_da: 'Thoracal rotation', category: 'mobility', muscle_groups: ['thoracic spine'], secondary_muscles: ['core'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Rotate upper back while kneeling.', form_cues: ['Hand behind head','Rotate only upper back'] },
  { name: 'Wall Slides', name_da: 'Væg slides', category: 'mobility', muscle_groups: ['shoulders'], secondary_muscles: ['upper back'], equipment: ['wall'], difficulty: 'beginner', instructions: 'Slide arms up and down wall.', form_cues: ['Back flat on wall','Arms stay on wall'] },
  { name: 'Band Pull-Apart Warm Up', name_da: 'Band pull-apart opvarmning', category: 'mobility', muscle_groups: ['rear delts'], secondary_muscles: ['rhomboids'], equipment: ['resistance band'], difficulty: 'beginner', instructions: 'Light band pull-aparts for warm up.', form_cues: ['High reps','Light resistance'] },
  { name: 'Banded Shoulder Dislocate', name_da: 'Banded skulder dislocate', category: 'mobility', muscle_groups: ['shoulders'], secondary_muscles: ['chest','upper back'], equipment: ['resistance band'], difficulty: 'beginner', instructions: 'Rotate band over and behind head.', form_cues: ['Wide grip','Slow controlled motion'] },
  { name: 'Ankle Mobilization', name_da: 'Ankel mobilisering', category: 'mobility', muscle_groups: ['ankles'], secondary_muscles: ['calves'], equipment: ['bodyweight','wall'], difficulty: 'beginner', instructions: 'Drive knee over toe against wall.', form_cues: ['Heel stays on floor','Push knee forward'] },
  { name: 'Couch Stretch', name_da: 'Sofa stræk', category: 'mobility', muscle_groups: ['hip flexors'], secondary_muscles: ['quads'], equipment: ['bodyweight','wall'], difficulty: 'intermediate', instructions: 'Rear foot against wall, lunge position.', form_cues: ['Back foot on wall','Squeeze glute'] },
  { name: 'Jefferson Curl', name_da: 'Jefferson curl', category: 'mobility', muscle_groups: ['hamstrings'], secondary_muscles: ['spine','lower back'], equipment: ['light dumbbell'], difficulty: 'intermediate', instructions: 'Slowly roll spine down vertebra by vertebra.', form_cues: ['Very light weight','Slow segmental movement'] },
  { name: 'Scorpion Stretch', name_da: 'Skorpion stræk', category: 'mobility', muscle_groups: ['hip flexors'], secondary_muscles: ['thoracic spine','chest'], equipment: ['bodyweight'], difficulty: 'intermediate', instructions: 'Lie face down, reach foot across to opposite side.', form_cues: ['Keep shoulders down','Reach slowly'] },
  { name: 'Deep Squat Hold', name_da: 'Dyb squat hold', category: 'mobility', muscle_groups: ['hips'], secondary_muscles: ['ankles','quads'], equipment: ['bodyweight'], difficulty: 'beginner', instructions: 'Sit in deep squat position, hold.', form_cues: ['Heels on floor','Push knees out'] },
  { name: 'Lacrosse Ball Pec Release', name_da: 'Lacrosse bold bryst release', category: 'mobility', muscle_groups: ['chest'], secondary_muscles: ['front delts'], equipment: ['lacrosse ball','wall'], difficulty: 'beginner', instructions: 'Pin ball against wall on chest, apply pressure.', form_cues: ['Find tender spots','30-60 seconds per spot'] }
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    // Check if exercises already exist
    const { count } = await supabase.from("exercises").select("*", { count: "exact", head: true });
    
    if (count && count > 50) {
      return new Response(JSON.stringify({ message: `Already ${count} exercises in database. Skipping seed.` }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Insert in batches of 50
    const batchSize = 50;
    let inserted = 0;
    for (let i = 0; i < exercises.length; i += batchSize) {
      const batch = exercises.slice(i, i + batchSize).map(e => ({ ...e, is_custom: false }));
      const { error } = await supabase.from("exercises").insert(batch);
      if (error) throw error;
      inserted += batch.length;
    }

    return new Response(JSON.stringify({ success: true, inserted, total: exercises.length }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
